

param={
		"rbc count":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"4.50-6.50"

		},
		"haemoglobin":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"13-16"
		},
		"packed cell volume":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"40-54"
		},
		"mcv":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"82-92"
		},
		"mch":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"mchc":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"32-36"
		},
		"rdw":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"11.6-13.7"
		},
		"platelet":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"150-400"
		},
		"mpv":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"7.8-11.0"
		},
		"pct":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"0.19-0.36"
		},
		"pdw":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"15.5-17.10"
		},
		"total count":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"4000-11000"
		},
		"neutrophil":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"lymphocyte":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"eosinophil":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"monocyte":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"basophils":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"27-32"
		},
		"globulins":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"2.0-3.6"

		},
		"albumin":{
			"age":False,
			"gender":False,
			"range":False,
			"data":True,
			"value":"3.5-5"
		}

}
